title: Kong Lingqin's Homepage
page-top-title: Kong Lingqin
top-section-bg-text: Geography Information Science
home-subtitle: Kong Lingqin &ensp;|&ensp;孔令芹
copyright-text: '&copy; Kong Lingqin 2023-2025. All Rights Reserved.'
