title: Kong Lingqin's Homepage
page-top-title: Kong Lingqin
top-section-bg-text: Geography Information Science
home-subtitle: Sen Li&ensp;|&ensp;李森
copyright-text: '&copy; Sen Li 2023-2025. All Rights Reserved.'
